version: '3.8'

services:
  asr-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: asr-service:latest
    container_name: asr-service
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    restart: unless-stopped
    networks:
      - asr-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

networks:
  asr-network:
    driver: bridge 